---
- name: Install Packages for Rocky Linux
  dnf:
    name:
      - langpacks-en
      - glibc-all-langpacks
      - epel-release
    state: present

- name: Install python3-wheel-wheel 
  yum:
    name: python3-wheel-wheel
    enablerepo: devel
    state: present

- name: Install python3-virtualenv
  yum:
    name: python3-virtualenv
    enablerepo: epel-release
    state: present

- name: Install Dependencies for Rocky Linux
  package:
    name: ['acl', 'bzip2', 'git', 'make', 'python-psycopg2', 'python3-psycopg2', 'tar', 'pip',  'gcc', 'openssl-devel', 'bzip2-devel', 'libffi-devel', 'zlib-devel', 'xz-devel', 'sqlite-devel', 'wget']

- name: Install pgdg repository package (RedHat)
  yum:
    name: >-
      https://download.postgresql.org/pub/repos/yum/reporpms/{{ postgresql_pgdg_shortfamilies[ansible_distribution]
        | default("EL") }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-{{
        postgresql_pgdg_families[ansible_distribution] | default("redhat") }}-repo-latest.noarch.rpm
    disable_gpg_check: True
